name: Fraud Detection CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
    test_and_build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codeS
              uses: actions/checkout@v3  #

            - name: set up python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'

            - name: Install dependencies
              run: pip install -r requirements_api.txt

            - name: Run tests
              run: python -m pytest tests/ -v -s

            - name: Build Docker image
              run: docker build -t fraud-detection-api .

            - name: Verify API imports
              run: |
                python -c "
                import sys
                sys.path.insert(0, '.')
                from api.model_utils import preprocess_input,get_risk_level
                print('Imports ok')"


